#!/bin/bash

# Mac Audio Streamer Setup Script
# This script automatically configures the project for your local network

echo "🎵 Mac Audio Streamer Setup"
echo "=========================="
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js first:"
    echo "   Visit: https://nodejs.org/"
    exit 1
fi

# Check if FFmpeg is installed
if ! command -v ffmpeg &> /dev/null; then
    echo "❌ FFmpeg is not installed. Please install FFmpeg first:"
    echo "   Run: brew install ffmpeg"
    exit 1
fi

echo "✅ Node.js and FFmpeg are installed"
echo ""

# Get local IP address
echo "🔍 Detecting your local IP address..."
LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')

if [ -z "$LOCAL_IP" ]; then
    echo "❌ Could not detect your local IP address"
    echo "   Please make sure you're connected to WiFi"
    exit 1
fi

echo "✅ Found your local IP: $LOCAL_IP"
echo ""

# Install dependencies
echo "📦 Installing Node.js dependencies..."
npm install

if [ $? -ne 0 ]; then
    echo "❌ Failed to install dependencies"
    exit 1
fi

echo "✅ Dependencies installed"
echo ""

# Update the QR code with their IP
echo "🔧 Updating QR code with your IP address..."
sed -i '' "s/192\.168\.0\.101/$LOCAL_IP/g" index.html

if [ $? -ne 0 ]; then
    echo "❌ Failed to update IP address in index.html"
    exit 1
fi

echo "✅ QR code updated with IP: $LOCAL_IP"
echo ""

# Create a simple start script
echo "📝 Creating start script..."
cat > start-server.sh << EOF
#!/bin/bash
echo "🎵 Starting Mac Audio Streamer..."
echo "📱 Your iPhone can connect to: $LOCAL_IP:3001"
echo "🌐 QR code available at: http://localhost:3000"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

# Start both servers
node udp-server.js &
UDP_PID=\$!

node qr-server.js &
QR_PID=\$!

# Function to cleanup on exit
cleanup() {
    echo ""
    echo "🛑 Stopping servers..."
    kill \$UDP_PID \$QR_PID 2>/dev/null
    exit 0
}

# Trap Ctrl+C
trap cleanup SIGINT

# Wait for processes
wait
EOF

chmod +x start-server.sh

echo "✅ Start script created"
echo ""

# Create README for users
echo "📖 Creating setup instructions..."
cat > SETUP_INSTRUCTIONS.md << EOF
# Mac Audio Streamer - Setup Complete! 🎵

## Your Configuration:
- **Local IP**: $LOCAL_IP
- **UDP Port**: 3001
- **QR Code Port**: 3000

## How to Use:

### 1. Start the Server:
\`\`\`bash
./start-server.sh
\`\`\`

### 2. Open QR Code:
- Go to: http://localhost:3000
- Or scan the QR code with your iPhone

### 3. Connect iPhone:
- Open the AudioReceiver app
- Tap "Scan QR Code"
- Point camera at the QR code
- Tap "Start Receiving"

### 4. Enjoy Audio Streaming! 🎧

## Requirements:
- Mac with Node.js and FFmpeg
- iPhone with AudioReceiver app
- Both devices on same WiFi network

## Troubleshooting:
- Make sure both devices are on the same WiFi
- Check that port 3001 is not blocked by firewall
- Restart the server if connection fails

## Stop the Server:
Press \`Ctrl+C\` in the terminal where the server is running.

---
*Generated by setup script on $(date)*
EOF

echo "✅ Setup instructions created"
echo ""

echo "🎉 Setup Complete!"
echo "=================="
echo ""
echo "Your Mac Audio Streamer is ready to use!"
echo ""
echo "📱 Your iPhone can connect to: $LOCAL_IP:3001"
echo "🌐 QR code will be available at: http://localhost:3000"
echo ""
echo "To start the server, run:"
echo "  ./start-server.sh"
echo ""
echo "📖 See SETUP_INSTRUCTIONS.md for detailed usage instructions"
echo ""
echo "Happy streaming! 🎵"
